title: Brett Daley's Homepage
description: "Brett Daley: Computer scientist and engineer researching AI and reinforcement learning."
url: https://brett-daley.github.io
lang: en_US

plugins:
    - jekyll-seo-tag
